repos:
  - repo: local
    hooks:
      - id: oxlint
        name: oxlint (staged)
        entry: pnpm exec oxlint --deny-warnings
        language: system
        types_or: [javascript, jsx]
        pass_filenames: true
      - id: prettier
        name: prettier (staged)
        entry: pnpm exec prettier --single-quote --write
        language: system
        types_or: [javascript, jsx, json, css, scss, markdown]
        pass_filenames: true
